# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModelPrediction.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_ReuseFaeModel(object):
    def setupUi(self, ReuseFaeModel):
        ReuseFaeModel.setObjectName("ReuseFaeModel")
        ReuseFaeModel.resize(932, 772)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(ReuseFaeModel)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(ReuseFaeModel)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineTestFeatureMatrixLoader = QtWidgets.QLineEdit(ReuseFaeModel)
        self.lineTestFeatureMatrixLoader.setObjectName("lineTestFeatureMatrixLoader")
        self.horizontalLayout.addWidget(self.lineTestFeatureMatrixLoader)
        self.buttonLoadTestFeature = QtWidgets.QPushButton(ReuseFaeModel)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.buttonLoadTestFeature.setFont(font)
        self.buttonLoadTestFeature.setObjectName("buttonLoadTestFeature")
        self.horizontalLayout.addWidget(self.buttonLoadTestFeature)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(ReuseFaeModel)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineModelPath = QtWidgets.QLineEdit(ReuseFaeModel)
        self.lineModelPath.setObjectName("lineModelPath")
        self.horizontalLayout_2.addWidget(self.lineModelPath)
        self.buttonLoadModel = QtWidgets.QPushButton(ReuseFaeModel)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.buttonLoadModel.setFont(font)
        self.buttonLoadModel.setObjectName("buttonLoadModel")
        self.horizontalLayout_2.addWidget(self.buttonLoadModel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.comboNormalizer = QtWidgets.QComboBox(ReuseFaeModel)
        self.comboNormalizer.setObjectName("comboNormalizer")
        self.horizontalLayout_3.addWidget(self.comboNormalizer)
        self.comboDimensionReduction = QtWidgets.QComboBox(ReuseFaeModel)
        self.comboDimensionReduction.setObjectName("comboDimensionReduction")
        self.horizontalLayout_3.addWidget(self.comboDimensionReduction)
        self.comboFeatureSelector = QtWidgets.QComboBox(ReuseFaeModel)
        self.comboFeatureSelector.setObjectName("comboFeatureSelector")
        self.horizontalLayout_3.addWidget(self.comboFeatureSelector)
        self.spinBoxFeatureNumber = QtWidgets.QSpinBox(ReuseFaeModel)
        self.spinBoxFeatureNumber.setObjectName("spinBoxFeatureNumber")
        self.horizontalLayout_3.addWidget(self.spinBoxFeatureNumber)
        self.comboClassifier = QtWidgets.QComboBox(ReuseFaeModel)
        self.comboClassifier.setObjectName("comboClassifier")
        self.horizontalLayout_3.addWidget(self.comboClassifier)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.buttonPredict = QtWidgets.QPushButton(ReuseFaeModel)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(QtGui.QFont.Weight.Bold)
        self.buttonPredict.setFont(font)
        self.buttonPredict.setObjectName("buttonPredict")
        self.verticalLayout.addWidget(self.buttonPredict)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableResult = QtWidgets.QTableWidget(ReuseFaeModel)
        self.tableResult.setMinimumSize(QtCore.QSize(300, 0))
        self.tableResult.setObjectName("tableResult")
        self.tableResult.setColumnCount(0)
        self.tableResult.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableResult)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkAutoCutoff = QtWidgets.QCheckBox(ReuseFaeModel)
        self.checkAutoCutoff.setChecked(True)
        self.checkAutoCutoff.setObjectName("checkAutoCutoff")
        self.horizontalLayout_4.addWidget(self.checkAutoCutoff)
        self.spinCutoff = QtWidgets.QDoubleSpinBox(ReuseFaeModel)
        self.spinCutoff.setMaximum(1.0)
        self.spinCutoff.setSingleStep(0.1)
        self.spinCutoff.setProperty("value", 0.5)
        self.spinCutoff.setObjectName("spinCutoff")
        self.horizontalLayout_4.addWidget(self.spinCutoff)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.canvas = MatplotlibWidget(ReuseFaeModel)
        self.canvas.setMinimumSize(QtCore.QSize(500, 500))
        self.canvas.setObjectName("canvas")
        self.verticalLayout_2.addWidget(self.canvas)
        self.comboCurve = QtWidgets.QComboBox(ReuseFaeModel)
        self.comboCurve.setObjectName("comboCurve")
        self.verticalLayout_2.addWidget(self.comboCurve)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)

        self.retranslateUi(ReuseFaeModel)
        QtCore.QMetaObject.connectSlotsByName(ReuseFaeModel)

    def retranslateUi(self, ReuseFaeModel):
        _translate = QtCore.QCoreApplication.translate
        ReuseFaeModel.setWindowTitle(_translate("ReuseFaeModel", "Reuse FAE Model"))
        self.label.setText(_translate("ReuseFaeModel", "Test Feature Matrix"))
        self.buttonLoadTestFeature.setText(_translate("ReuseFaeModel", "Load"))
        self.label_3.setText(_translate("ReuseFaeModel", "Developed Models"))
        self.buttonLoadModel.setText(_translate("ReuseFaeModel", "Load"))
        self.buttonPredict.setText(_translate("ReuseFaeModel", "Predict"))
        self.checkAutoCutoff.setText(_translate("ReuseFaeModel", "Auto Cutoff"))
from MatplotlibWidget import MatplotlibWidget
